name: blog_post_flask
channels:
  - conda-forge
dependencies:
  - flask
  - ipykernel
  - pip
  - python
  - flask-bcrypt
  - flask-login
  - flask-wtf
  - flask-sqlalchemy
  - email_validator
  - pip:
    - black
    - pre-commit
